Repository depapp/IndoGitHubers, pull requests merged in 2023-10, with the labels that each got.

#7 Component refactor
  .eslintrc.cjs
  package-lock.json
  src/App.jsx
  src/components/Header.jsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 Add how to setup
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#10 - add filter buton
  src/App.jsx
  src/components/Header.jsx
  src/index.css
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#12 added contributors list to the readme
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#16 Update App.jsx
  src/App.jsx
Labels: hacktoberfest, hacktoberfest-accepted
